"""rename columns completed_lessons

Revision ID: 23078b110986
Revises: 9c3fc214cfb1
Create Date: 2026-07-21 15:46:37.839239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23078b110986'
down_revision: Union[str, Sequence[str], None] = '9c3fc214cfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_lessons', sa.Column('student_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('completed_lessons_user_id_fkey'), 'completed_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'completed_lessons', 'users', ['student_id'], ['id'])
    op.drop_column('completed_lessons', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_lessons', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'completed_lessons', type_='foreignkey')
    op.create_foreign_key(op.f('completed_lessons_user_id_fkey'), 'completed_lessons', 'users', ['user_id'], ['id'])
    op.drop_column('completed_lessons', 'student_id')
    # ### end Alembic commands ###
