"""Add lesson column assignment

Revision ID: 3a83dabaad41
Revises: 719495d958b7
Create Date: 2026-07-21 11:55:32.656275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a83dabaad41'
down_revision: Union[str, Sequence[str], None] = '719495d958b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('assignment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'assignment')
    # ### end Alembic commands ###
