"""add column name for lessons table

Revision ID: 46f0f544e05b
Revises: ec99dc73b7ff
Create Date: 2026-07-21 16:05:44.078098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f0f544e05b'
down_revision: Union[str, Sequence[str], None] = 'ec99dc73b7ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('name', sa.String(), server_default='Урок', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'name')
    # ### end Alembic commands ###
