"""Add lesson column number

Revision ID: dd0aab988d73
Revises: 3a83dabaad41
Create Date: 2026-07-21 12:05:54.351782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0aab988d73'
down_revision: Union[str, Sequence[str], None] = '3a83dabaad41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('number', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'lessons', ['number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='unique')
    op.drop_column('lessons', 'number')
    # ### end Alembic commands ###
