"""rename foreign key completed_lessons

Revision ID: ec99dc73b7ff
Revises: 23078b110986
Create Date: 2026-07-21 15:49:55.811602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec99dc73b7ff'
down_revision: Union[str, Sequence[str], None] = '23078b110986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('completed_lessons_student_id_fkey'), 'completed_lessons', type_='foreignkey')
    op.create_foreign_key(None, 'completed_lessons', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'completed_lessons', type_='foreignkey')
    op.create_foreign_key(op.f('completed_lessons_student_id_fkey'), 'completed_lessons', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###
